
  
site_name: Resident Evil 2 (Remake) Soluce Rang S+
docs_dir: docs
nav:
  - Accueil: index.md
  - "Claire":
    - "Scénario A": ClaireA.md
    - "Scénario B": ClaireB.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.top
    - navigation.tabs.sticky
    - toc.integrate 


markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - toc:
      toc_depth: 2

plugins:
  - with-pdf
  - glightbox
