
site_dir: public  
site_name: Naouak 
docs_dir: 'docs/'
nav:
  - Accueil: index.md
  - "Resident Evil 2 (Remake)":
    - "Claire":
      - "Scénario A": ClaireA.md
      - "Scénario B": ClaireB.md

theme:
  name: material
  nav_style: light
  navigation_depth: 4
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.top
    - toc.integrate # Table Of Content, table des matières intégrée dans la barre verticale de navigation
  palette:
    - scheme: default
      primary: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  language: fr
use_directory_urls: false


markdown_extensions:
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true 
  - admonition
  - def_list
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: True
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - toc:
      toc_depth: 2

plugins:
  - to-pdf:
      toc_title: "Sommaire"
      toc_level: 4
      author: Scie à métaux
      cover_subtitle: Guides & Astuces
      download_link: header
  - glightbox






